### PR TITLE
[Issue 28] Linux not rendering

### PR DESCRIPTION
**Pull request by growlercab**
This is a trivial fix for the Linux rendering issue I encountered with the latest Dgame.

**NOTE**: I have only tested this on Arch Linux x86_64.

### CODE REVIEW

**Comment by growlercab** [comment]
I just realised you may find commenting out this line fixes the MAC blank-screen issue as it did on Linux.

`SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS,SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG);`

This PR only fixes the linux render issue by bypassing the entire block that selects the GL version. The real fix for all platforms might be just don't set that forward compatible bit.

I don't have a MAC to test this theory, sorry. If you do get a chance to test it and it works, free to reject this PR.

However, I'd rather be running GL 4.5 than GL 3.0 if I can and this PR lets me do that :)

**Comment by growlercab** [comment]
OK my idea didn't work on MAC as reported in the dlang forums:

http://forum.dlang.org/thread/cwmvdndazklelixtqrru@forum.dlang.org?page=5

This PR will only fix Dgame on linux and should not break MAC any further.

**Comment by Dgame** [comment]
Then I have no clue what fails on Mac. :/

**Comment by growlercab** [comment]
No, me neither. It's hard without a MAC to try things out too so I cannot help much unfortunately.

Do you think you will merge this PR or should I just close it? 

It fixes Linux, which is currently broken in 0.4.2, but it's only a patch job until a proper x-platform can be worked out.

**Comment by Dgame** [comment]
Since I have no clue how to fix that on a Mac yet, I will merge it. Thank you again.

**Comment by growlercab** [comment]
thanks for merging, I just tested and Linux is now working again in 0.4.3 :)

**Comment by Dgame** [comment]
Nice to hear! :)

**Comment by rikkimax** [comment]
@Dgame Change that from 3.0 to 3.2, I suspect that'll work on OSX.
https://github.com/Devisualization/window/blob/master/cocoa_library/project/dwc-osx/context.m#L37

**Comment by Dgame** [comment]
I already suggested that. According to him, this does not change anything:
http://forum.dlang.org/thread/cwmvdndazklelixtqrru@forum.dlang.org?page=3#post-djwtqcjnxnnyfvygalol:40forum.dlang.org

**Pull request merged**
