### PR TITLE
Dub package

### PR DESCRIPTION
**Pull request by growlercab**
I've only tested this with Arch Linux X86_64 DMD 2.066.1 running the main.d example.

**NOTE** I have had to change some import paths to match the Derelict pulled in by DUB and some access to SDL_Color. The diffs have all the details.

I changed the extensions in the samples folder to be lower case so the example would run, what with *nix being case-sensitive and all that.

I've also added LICENSE file in prep for dub package registry. I just pulled it from the Dgame web page. I hope that's OK

If you prefer not to pull this because it changes too much just for DUB, feel free to cherry pick what's useful as you see fit.

---

To build the example with dub:

1. cd /your/Dgame/folder/
2. dub build --compiler=dmd -cexample 

Dub will pull in the required Derelict packages. 

To use Dgame as a library with dub it will need to be added to the local DUB registry. I think this is because it's not a registered DUB package. Something like the following untested set of steps should do it.

1. cd /parent/dir/to/Dgame/folder/
2. dub add-local Dgame 0.3.2
(or whatever version number it should be)

[edit] The "-cexamlpe" dub target will produce a binary call  "dgame-example".

### CODE REVIEW

**Comment by Dgame** [comment]
Wow, that really nice of you. Thank you! I will look over it today.

**Comment by Dgame** [comment]
@growlercab  Since I'm using the Derelict lib files inside of the app.d, how can I access them after dub has installed the needed derelict packages?

**Comment by Dgame** [comment]
Forget it. It works now. I will merge this PR, do some adaptations and then I will publish Dgame on DUB.
Thank you for your effort.

**Comment by growlercab** [comment]
I'm glad it was useful! Thanks :)

**Pull request merged**
